language: c

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - gcc-4.9
      - g++-4.9
      - gcc-5
      - g++-5
      - gfortran-5
      - ninja

env:
  global:
    - CCACHE_CPP2=yes
    - J=2
  matrix:
    - 
    - SHARED_LIBS=OFF
    - GVER=5
    - GVER=4.9 COVERAGE=ON

before_install:
 - if [[ ${GVER} ]]; then export CC=gcc-${GVER}; export CXX=g++-${GVER}; export FC=gfortran-${GVER}; fi
 - if [[ ${COVERAGE}  ]]; then pip install --user codecov; fi 

script: 
   - mkdir build && cd build &&
     cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_TESTING=ON ${COVERAGE:+-DENABLE_COVERAGE_BUILD=ON} ${SHARED_LIBS:+-DBUILD_SHARED_LIBS=${SHARED_LIBS}} .. && 
     make -j${J} && make test && make install DESTDIR=${PWD}

after_success:
  - if [[ ${COVERAGE} ]]; then codecov --gcov-exec gcov-${GVER}; fi

cache:
  - ccache

compiler:
  - gcc
